### ISSUE TITLE
Bug: Values changing slightly

### ISSUE THREAD

**Issue by probablykasper** [viktorstrate/color-picker-plus#3]
![bug](https://user-images.githubusercontent.com/11315492/41823999-3e4fa426-7809-11e8-820b-1813bfe3c594.gif)
As you see in the gif, when I click on some text fields after selecting a color, the values seem to change. Can't really see a pattern, but it happens most of the times.

**Comment by viktorstrate** [comment]
This happends when the color is converted between RGB/HEX and HSB, when you leave the hex text field, the colors are recalculated using the given hex-color, probably because of some math rounding bugs, I will try and find a good solution to this.

Btw, thank you for your suggestions, I will surely try to implement most of them 😁 👍
